-- GENERATED FILE -- do not hand-edit.
-- Produced by spawnmasons/import_tools/gen_lua_data.py from
-- mc_to_mcl.json (+ mapart/palette.json, mcl_nodes_literal.txt).
-- Re-run that script after changing mc_to_mcl.json; this file
-- exists only so palette.lua doesn't need a JSON parser at runtime.

return {
	["colors"] = {
		["white"] = "white",
		["orange"] = "orange",
		["magenta"] = "magenta",
		["light_blue"] = "light_blue",
		["yellow"] = "yellow",
		["lime"] = "lime",
		["pink"] = "pink",
		["gray"] = "grey",
		["light_gray"] = "silver",
		["cyan"] = "cyan",
		["purple"] = "purple",
		["blue"] = "blue",
		["brown"] = "brown",
		["green"] = "green",
		["red"] = "red",
		["black"] = "black",
	},
	["shulker_colors"] = {
		["white"] = "white",
		["orange"] = "orange",
		["magenta"] = "magenta",
		["light_blue"] = "lightblue",
		["yellow"] = "yellow",
		["lime"] = "green",
		["pink"] = "pink",
		["gray"] = "dark_grey",
		["light_gray"] = "grey",
		["cyan"] = "cyan",
		["purple"] = "violet",
		["blue"] = "blue",
		["brown"] = "brown",
		["green"] = "dark_green",
		["red"] = "red",
		["black"] = "black",
	},
	["wood_species"] = {
		"acacia",
		"birch",
		"cherry",
		"dark_oak",
		"jungle",
		"mangrove",
		"oak",
		"spruce",
	},
	["stair_slab_subname"] = {
		["acacia"] = "acacia",
		["birch"] = "birch",
		["cherry"] = "cherry_blossom",
		["dark_oak"] = "dark_oak",
		["jungle"] = "jungle",
		["mangrove"] = "mangrove",
		["oak"] = "oak",
		["spruce"] = "spruce",
		["stone"] = "stone_rough",
		["cobblestone"] = "cobble",
		["brick"] = "brick_block",
		["sandstone"] = "sandstone",
		["red_sandstone"] = "redsandstone",
		["smooth_sandstone"] = "sandstonesmooth2",
		["cut_sandstone"] = "sandstonesmooth",
		["stone_brick"] = "stonebrick",
		["mossy_stone_brick"] = "stonebrickmossy",
		["nether_brick"] = "nether_brick",
		["purpur"] = "purpur_block",
		["quartz"] = "quartzblock",
		["smooth_quartz"] = "quartz_smooth",
		["andesite"] = "andesite_smooth",
		["granite"] = "granite_smooth",
		["diorite"] = "diorite_smooth",
		["polished_blackstone"] = "blackstone_polished",
		["polished_blackstone_brick"] = "blackstone_brick_polished",
		["cobbled_deepslate"] = "deepslate_cobbled",
		["polished_deepslate"] = "deepslate_polished",
		["deepslate_brick"] = "deepslate_bricks",
		["deepslate_tile"] = "deepslate_tiles",
		["mud_brick"] = "mud_brick",
		["prismarine_dark"] = "prismarine_dark",
		["dark_prismarine"] = "prismarine_dark",
		["blackstone"] = "blackstone",
		["polished_andesite"] = "andesite_smooth",
		["polished_granite"] = "granite_smooth",
		["polished_diorite"] = "diorite_smooth",
	},
	["smooth_stone_slab"] = "mcl_stairs:slab_stone",
	["wall_subname"] = {
		["cobblestone"] = "cobble",
		["mossy_cobblestone"] = "mossycobble",
		["stone_brick"] = "stonebrick",
		["mossy_stone_brick"] = "stonebrickmossy",
		["andesite"] = "andesite",
		["diorite"] = "diorite",
		["granite"] = "granite",
		["brick"] = "brick",
		["sandstone"] = "sandstone",
		["red_sandstone"] = "redsandstone",
		["mud_brick"] = "mudbrick",
	},
	["head_name"] = {
		["zombie"] = "zombie",
		["skeleton"] = "skeleton",
		["wither_skeleton"] = "wither_skeleton",
		["creeper"] = "creeper",
		["dragon"] = "dragon",
	},
	["special"] = {
		["_readme"] = "Properties that change WHICH node to use, not just how to orient/render it (facing/half/shape/axis/hinge/open/waterlogged/rotation/snowy/age/etc. are all orientation or state, not identity, and are deliberately NOT special-cased here -- see palette_report.md 'Properties that turned out not to matter').",
		["slab_type"] = {
			["_readme"] = "Applies to every *_slab. Target is computed from the already-resolved single-slab node name (mcl_stairs:slab_<subname>).",
			["bottom"] = "{slab}",
			["top"] = "{slab}_top",
			["double"] = "{slab}_double",
		},
		["furnace_lit"] = {
			["_readme"] = "mods/ITEMS/mcl_furnaces/init.lua registers the unlit node as the base name and the lit one as '<name>_active'.",
			["false"] = "mcl_furnaces:furnace",
			["true"] = "mcl_furnaces:furnace_active",
		},
		["bed_part"] = {
			["_readme"] = "mods/ITEMS/mcl_beds/api.lua register_bed() registers '<name>_bottom' and '<name>_top'. Minecraft's bed 'part' property is 'head'/'foot'; the head end is the pillow end, which is the 'top' node in Mineclonia's naming (best-effort pairing, not independently confirmed against in-game pillow orientation).",
			["foot"] = "{bed}_bottom",
			["head"] = "{bed}_top",
		},
		["piston_extended"] = {
			["_readme"] = "mods/ITEMS/REDSTONE/mcl_pistons/nodes.lua registers 'piston_off'/'piston_on' (unextended/extended).",
			["false"] = "mcl_pistons:piston_off",
			["true"] = "mcl_pistons:piston_on",
		},
		["sticky_piston_extended"] = {
			["_readme"] = "Same mod, 'piston_sticky_off'/'piston_sticky_on'.",
			["false"] = "mcl_pistons:piston_sticky_off",
			["true"] = "mcl_pistons:piston_sticky_on",
		},
		["piston_head_type"] = {
			["_readme"] = "The piston head/arm node: 'piston_pusher' (normal) / 'piston_pusher_sticky'.",
			["normal"] = "mcl_pistons:piston_pusher",
			["sticky"] = "mcl_pistons:piston_pusher_sticky",
		},
		["observer_powered"] = {
			["_readme"] = "mods/ITEMS/REDSTONE/mcl_observers/*.lua registers 'observer_off'/'observer_on' (there are also facing-specific up/down variants not modeled here).",
			["false"] = "mcl_observers:observer_off",
			["true"] = "mcl_observers:observer_on",
		},
		["redstone_torch_lit"] = {
			["_readme"] = "mods/ITEMS/REDSTONE/mcl_redstone_torch/init.lua: mcl_torches.register_torch({name='redstone_torch_off'/'redstone_torch_on'}) -- itemstring is '<modname>:<name>', modname is mcl_redstone_torch here (get_current_modname() at the actual call site, NOT the mcl_torches module that defines register_torch -- this is what caused the original wrong 'mcl_redstone:torch' guess).",
			["false"] = "mcl_redstone_torch:redstone_torch_off",
			["true"] = "mcl_redstone_torch:redstone_torch_on",
		},
		["redstone_wall_torch_lit"] = {
			["_readme"] = "register_torch() appends '_wall' to the floor itemstring for the wall variant.",
			["false"] = "mcl_redstone_torch:redstone_torch_off_wall",
			["true"] = "mcl_redstone_torch:redstone_torch_on_wall",
		},
		["redstone_lamp_lit"] = {
			["_readme"] = "mods/ITEMS/REDSTONE/mcl_redstone_lamp/init.lua registers 'lamp_off'/'lamp_on', NOT 'redstone_lamp'/'redstone_lamp_active' (that was a wrong guess-by-analogy to the furnace pattern).",
			["false"] = "mcl_redstone_lamp:lamp_off",
			["true"] = "mcl_redstone_lamp:lamp_on",
		},
		["nether_wart_age"] = {
			["_readme"] = "mods/ITEMS/mcl_nether/nether_wart.lua registers nether_wart_0/_1/_2 for the growing stages and plain 'nether_wart' for the mature (age 3) stage.",
			["0"] = "mcl_nether:nether_wart_0",
			["1"] = "mcl_nether:nether_wart_1",
			["2"] = "mcl_nether:nether_wart_2",
			["3"] = "mcl_nether:nether_wart",
		},
	},
	["exact"] = {
		["terracotta"] = "mcl_colorblocks:hardened_clay",
		["iron_door"] = "mcl_doors:iron_door",
		["iron_trapdoor"] = "mcl_doors:iron_trapdoor",
		["nether_brick_fence"] = "mcl_fences:nether_brick_fence",
		["stone"] = "mcl_core:stone",
		["andesite"] = "mcl_core:andesite",
		["granite"] = "mcl_core:granite",
		["diorite"] = "mcl_core:diorite",
		["polished_andesite"] = "mcl_core:andesite_smooth",
		["polished_granite"] = "mcl_core:granite_smooth",
		["polished_diorite"] = "mcl_core:diorite_smooth",
		["bedrock"] = "mcl_core:bedrock",
		["dirt"] = "mcl_core:dirt",
		["coarse_dirt"] = "mcl_core:coarse_dirt",
		["dirt_path"] = "mcl_core:grass_path",
		["grass_block"] = "mcl_core:dirt_with_grass",
		["gravel"] = "mcl_core:gravel",
		["sand"] = "mcl_core:sand",
		["red_sand"] = "mcl_core:redsand",
		["clay"] = "mcl_core:clay",
		["ice"] = "mcl_core:ice",
		["packed_ice"] = "mcl_core:packed_ice",
		["obsidian"] = "mcl_core:obsidian",
		["netherrack"] = "mcl_nether:netherrack",
		["nether_bricks"] = "mcl_nether:nether_brick",
		["red_nether_bricks"] = "mcl_nether:red_nether_brick",
		["nether_quartz_ore"] = "mcl_nether:quartz_ore",
		["nether_wart_block"] = "mcl_nether:nether_wart_block",
		["soul_sand"] = "mcl_nether:soul_sand",
		["glowstone"] = "mcl_nether:glowstone",
		["magma_block"] = "mcl_nether:magma",
		["end_stone"] = "mcl_end:end_stone",
		["end_stone_bricks"] = "mcl_end:end_bricks",
		["purpur_block"] = "mcl_end:purpur_block",
		["purpur_pillar"] = "mcl_end:purpur_pillar",
		["dragon_egg"] = "mcl_end:dragon_egg",
		["chorus_plant"] = "mcl_end:chorus_plant",
		["chorus_flower"] = "mcl_end:chorus_flower",
		["quartz_block"] = "mcl_nether:quartz_block",
		["chiseled_quartz_block"] = "mcl_nether:quartz_chiseled",
		["quartz_pillar"] = "mcl_nether:quartz_pillar",
		["cobblestone"] = "mcl_core:cobble",
		["mossy_cobblestone"] = "mcl_core:mossycobble",
		["stone_bricks"] = "mcl_core:stonebrick",
		["cracked_stone_bricks"] = "mcl_core:stonebrickcracked",
		["chiseled_stone_bricks"] = "mcl_core:stonebrickcarved",
		["mossy_stone_bricks"] = "mcl_core:stonebrickmossy",
		["infested_stone"] = "mcl_monster_eggs:monster_egg_stone",
		["bricks"] = "mcl_core:brick_block",
		["sandstone"] = "mcl_core:sandstone",
		["chiseled_sandstone"] = "mcl_core:sandstonecarved",
		["cut_sandstone"] = "mcl_core:sandstonesmooth",
		["red_sandstone"] = "mcl_core:redsandstone",
		["chiseled_red_sandstone"] = "mcl_core:redsandstonecarved",
		["cut_red_sandstone"] = "mcl_core:redsandstonesmooth",
		["prismarine"] = "mcl_ocean:prismarine",
		["prismarine_bricks"] = "mcl_ocean:prismarine_brick",
		["dark_prismarine"] = "mcl_ocean:prismarine_dark",
		["sea_lantern"] = "mcl_ocean:sea_lantern",
		["sponge"] = "mcl_sponges:sponge",
		["wet_sponge"] = "mcl_sponges:sponge_wet",
		["coal_ore"] = "mcl_core:stone_with_coal",
		["coal_block"] = "mcl_core:coalblock",
		["iron_ore"] = "mcl_core:stone_with_iron",
		["iron_block"] = "mcl_core:ironblock",
		["gold_ore"] = "mcl_core:stone_with_gold",
		["gold_block"] = "mcl_core:goldblock",
		["diamond_ore"] = "mcl_core:stone_with_diamond",
		["diamond_block"] = "mcl_core:diamondblock",
		["emerald_ore"] = "mcl_core:stone_with_emerald",
		["emerald_block"] = "mcl_core:emeraldblock",
		["lapis_ore"] = "mcl_core:stone_with_lapis",
		["lapis_block"] = "mcl_core:lapisblock",
		["redstone_ore"] = "mcl_core:stone_with_redstone",
		["bone_block"] = "mcl_core:bone_block",
		["hay_block"] = "mcl_farming:hay_block",
		["slime_block"] = "mcl_core:slimeblock",
		["snow"] = "mcl_core:snow",
		["snow_block"] = "mcl_core:snowblock",
		["cobweb"] = "mcl_core:cobweb",
		["bookshelf"] = "mcl_books:bookshelf",
		["water_cauldron"] = "mcl_cauldrons:cauldron",
		["cauldron"] = "mcl_cauldrons:cauldron",
		["glass"] = "mcl_core:glass",
		["iron_bars"] = "mcl_panes:bar",
		["glass_pane"] = "mcl_panes:pane_natural",
		["ladder"] = "mcl_core:ladder",
		["vine"] = "mcl_core:vine",
		["lily_pad"] = "mcl_flowers:waterlily",
		["mycelium"] = "mcl_core:mycelium",
		["podzol"] = "mcl_core:podzol",
		["farmland"] = "mcl_farming:soil",
		["wheat"] = "mcl_farming:wheat",
		["carrots"] = "mcl_farming:carrot",
		["potatoes"] = "mcl_farming:potato",
		["beetroots"] = "mcl_farming:beetroot",
		["sugar_cane"] = "mcl_core:reeds",
		["cactus"] = "mcl_core:cactus",
		["pumpkin"] = "mcl_farming:pumpkin",
		["carved_pumpkin"] = "mcl_farming:pumpkin_face",
		["jack_o_lantern"] = "mcl_farming:pumpkin_face_light",
		["melon"] = "mcl_farming:melon",
		["melon_stem"] = "mcl_farming:melontige_unconnect",
		["attached_melon_stem"] = "mcl_farming:melontige_linked_r",
		["pumpkin_stem"] = "mcl_farming:pumpkintige_unconnect",
		["attached_pumpkin_stem"] = "mcl_farming:pumpkintige_linked_r",
		["short_grass"] = "mcl_flowers:tallgrass",
		["tall_grass"] = "mcl_flowers:double_grass",
		["large_fern"] = "mcl_flowers:double_fern",
		["fern"] = "mcl_flowers:fern",
		["dead_bush"] = "mcl_core:deadbush",
		["dandelion"] = "mcl_flowers:dandelion",
		["poppy"] = "mcl_flowers:poppy",
		["blue_orchid"] = "mcl_flowers:blue_orchid",
		["allium"] = "mcl_flowers:allium",
		["azure_bluet"] = "mcl_flowers:azure_bluet",
		["red_tulip"] = "mcl_flowers:tulip_red",
		["orange_tulip"] = "mcl_flowers:tulip_orange",
		["white_tulip"] = "mcl_flowers:tulip_white",
		["pink_tulip"] = "mcl_flowers:tulip_pink",
		["oxeye_daisy"] = "mcl_flowers:oxeye_daisy",
		["sunflower"] = "mcl_flowers:sunflower",
		["lilac"] = "mcl_flowers:lilac",
		["peony"] = "mcl_flowers:peony",
		["rose_bush"] = "mcl_flowers:rose_bush",
		["brown_mushroom"] = "mcl_mushrooms:mushroom_brown",
		["red_mushroom"] = "mcl_mushrooms:mushroom_red",
		["brown_mushroom_block"] = "mcl_mushrooms:brown_mushroom_block_cap_111111",
		["red_mushroom_block"] = "mcl_mushrooms:red_mushroom_block_cap_111111",
		["mushroom_stem"] = "mcl_mushrooms:brown_mushroom_block_stem_full",
		["crafting_table"] = "mcl_crafting_table:crafting_table",
		["enchanting_table"] = "mcl_enchanting:table",
		["anvil"] = "mcl_anvils:anvil",
		["chipped_anvil"] = "mcl_anvils:anvil_damage_1",
		["damaged_anvil"] = "mcl_anvils:anvil_damage_2",
		["furnace"] = "mcl_furnaces:furnace",
		["chest"] = "mcl_chests:chest",
		["trapped_chest"] = "mcl_chests:trapped_chest",
		["ender_chest"] = "mcl_chests:ender_chest",
		["dripstone_block"] = "mcl_dripstone:dripstone_block",
		["grass"] = "mcl_flowers:tallgrass",
		["kelp"] = "mcl_ocean:kelp_dirt",
		["kelp_plant"] = "mcl_ocean:kelp_dirt",
		["lantern"] = "mcl_lanterns:lantern_floor",
		["campfire"] = "mcl_campfires:campfire",
		["lectern"] = "mcl_lectern:lectern",
		["chain"] = "mcl_lanterns:chain",
		["fletching_table"] = "mcl_fletching_table:fletching_table",
		["smithing_table"] = "mcl_smithing_table:table",
		["cartography_table"] = "mcl_cartography_table:cartography_table",
		["stonecutter"] = "mcl_stonecutter:stonecutter",
		["loom"] = "mcl_loom:loom",
		["grindstone"] = "mcl_grindstone:grindstone",
		["blast_furnace"] = "mcl_blast_furnace:blast_furnace",
		["smoker"] = "mcl_smoker:smoker",
		["barrel"] = "mcl_barrels:barrel_closed",
		["note_block"] = "mcl_noteblock:noteblock",
		["jukebox"] = "mcl_jukebox:jukebox",
		["tnt"] = "mcl_tnt:tnt",
		["beacon"] = "mcl_beacons:beacon",
		["spawner"] = "mcl_mobspawners:spawner",
		["flower_pot"] = "mcl_flowerpots:flower_pot",
		["cake"] = "mcl_cake:cake",
		["brewing_stand"] = "mcl_brewing:stand_000",
		["daylight_detector"] = "mcl_daylight_detector:daylight_detector",
		["oak_button"] = "mcl_buttons:button_oak_off",
		["stone_button"] = "mcl_buttons:button_stone_off",
		["oak_pressure_plate"] = "mcl_pressureplates:pressure_plate_oak_off",
		["stone_pressure_plate"] = "mcl_pressureplates:pressure_plate_stone_off",
		["light_weighted_pressure_plate"] = "mcl_pressureplates:pressure_plate_light_off",
		["heavy_weighted_pressure_plate"] = "mcl_pressureplates:pressure_plate_heavy_off",
		["rail"] = "mcl_minecarts:rail",
		["powered_rail"] = "mcl_minecarts:golden_rail",
		["detector_rail"] = "mcl_minecarts:detector_rail",
		["activator_rail"] = "mcl_minecarts:activator_rail",
		["redstone_wire"] = "mcl_redstone:redstone",
		["torch"] = "mcl_torches:torch",
		["wall_torch"] = "mcl_torches:torch_wall",
		["fire"] = "mcl_fire:fire",
		["redstone_block"] = "mcl_redstone_torch:redstoneblock",
		["deepslate"] = "mcl_deepslate:deepslate",
		["cobbled_deepslate"] = "mcl_deepslate:deepslate_cobbled",
		["polished_deepslate"] = "mcl_deepslate:deepslate_polished",
		["chiseled_deepslate"] = "mcl_deepslate:deepslate_chiseled",
		["deepslate_bricks"] = "mcl_deepslate:deepslate_bricks",
		["cracked_deepslate_bricks"] = "mcl_deepslate:deepslate_bricks_cracked",
		["deepslate_tiles"] = "mcl_deepslate:deepslate_tiles",
		["cracked_deepslate_tiles"] = "mcl_deepslate:deepslate_tiles_cracked",
		["reinforced_deepslate"] = "mcl_deepslate:deepslate_reinforced",
		["deepslate_coal_ore"] = "mcl_deepslate:deepslate_with_coal",
		["deepslate_iron_ore"] = "mcl_deepslate:deepslate_with_iron",
		["deepslate_copper_ore"] = "mcl_deepslate:deepslate_with_copper",
		["deepslate_gold_ore"] = "mcl_deepslate:deepslate_with_gold",
		["deepslate_redstone_ore"] = "mcl_deepslate:deepslate_with_redstone",
		["deepslate_emerald_ore"] = "mcl_deepslate:deepslate_with_emerald",
		["deepslate_lapis_ore"] = "mcl_deepslate:deepslate_with_lapis",
		["deepslate_diamond_ore"] = "mcl_deepslate:deepslate_with_diamond",
		["tuff"] = "mcl_deepslate:tuff",
		["copper_ore"] = "mcl_copper:stone_with_copper",
		["raw_iron_block"] = "mcl_raw_ores:raw_iron_block",
		["raw_gold_block"] = "mcl_raw_ores:raw_gold_block",
		["calcite"] = "mcl_amethyst:calcite",
		["smooth_basalt"] = "mcl_blackstone:basalt_smooth",
		["amethyst_block"] = "mcl_amethyst:amethyst_block",
		["budding_amethyst"] = "mcl_amethyst:budding_amethyst_block",
		["amethyst_cluster"] = "mcl_amethyst:amethyst_cluster",
		["small_amethyst_bud"] = "mcl_amethyst:small_amethyst_bud",
		["medium_amethyst_bud"] = "mcl_amethyst:medium_amethyst_bud",
		["large_amethyst_bud"] = "mcl_amethyst:large_amethyst_bud",
		["tinted_glass"] = "mcl_amethyst:tinted_glass",
		["moss_block"] = "mcl_lush_caves:moss",
		["moss_carpet"] = "mcl_lush_caves:moss_carpet",
		["azalea"] = "mcl_lush_caves:azalea",
		["flowering_azalea"] = "mcl_lush_caves:azalea_flowering",
		["cave_vines"] = "mcl_lush_caves:cave_vines",
		["cave_vines_plant"] = "mcl_lush_caves:cave_vines",
		["big_dripleaf"] = "mcl_lush_caves:dripleaf_big",
		["big_dripleaf_stem"] = "mcl_lush_caves:dripleaf_big_stem",
		["small_dripleaf"] = "mcl_lush_caves:dripleaf_small",
		["glow_lichen"] = "mcl_core:glow_lichen",
		["cornflower"] = "mcl_flowers:cornflower",
		["seagrass"] = "mcl_ocean:seagrass_dirt",
		["tall_seagrass"] = "mcl_ocean:seagrass_dirt",
		["bubble_column"] = "mcl_core:water_source",
		["spore_blossom"] = "mcl_lush_caves:spore_blossom",
		["smooth_stone"] = "mcl_core:stone_smooth",
		["smooth_sandstone"] = "mcl_core:sandstonesmooth2",
		["blackstone"] = "mcl_blackstone:blackstone",
		["gilded_blackstone"] = "mcl_blackstone:blackstone_gilded",
		["polished_blackstone_bricks"] = "mcl_blackstone:blackstone_brick_polished",
		["sculk"] = "mcl_sculk:sculk",
		["sculk_vein"] = "mcl_sculk:vein",
		["sculk_catalyst"] = "mcl_sculk:catalyst",
		["sculk_sensor"] = "mcl_sculk:sensor",
		["sculk_shrieker"] = "mcl_sculk:shrieker",
		["mud"] = "mcl_mud:mud",
		["packed_mud"] = "mcl_mud:packed_mud",
		["mud_bricks"] = "mcl_mud:mud_bricks",
		["rooted_dirt"] = "mcl_lush_caves:rooted_dirt",
		["powder_snow"] = "mcl_powder_snow:powder_snow",
		["scaffolding"] = "mcl_bamboo:scaffolding",
		["raw_copper_block"] = "mcl_copper:block_raw",
		["sweet_berry_bush"] = "mcl_farming:sweet_berry_bush_0",
		["azalea_leaves"] = "mcl_trees:leaves_azalea",
		["flowering_azalea_leaves"] = "mcl_trees:leaves_azalea_flowering",
		["crimson_nylium"] = "mcl_crimson:crimson_nylium",
		["crimson_roots"] = "mcl_crimson:crimson_roots",
		["crimson_fungus"] = "mcl_crimson:crimson_fungus",
		["weeping_vines"] = "mcl_crimson:weeping_vines",
		["weeping_vines_plant"] = "mcl_crimson:weeping_vines",
		["lightning_rod"] = "mcl_lightning_rods:rod",
		["sea_pickle"] = "mcl_ocean:sea_pickle_1_dead_brain_coral_block",
		["hanging_roots"] = "mcl_lush_caves:hanging_roots",
		["bee_nest"] = "mcl_beehives:bee_nest",
		["suspicious_sand"] = "mcl_sus_nodes:sand",
		["lodestone"] = "mcl_compass:lodestone",
		["lily_of_the_valley"] = "mcl_flowers:lily_of_the_valley",
		["decorated_pot"] = "mcl_pottery_sherds:pot",
		["infested_deepslate"] = "mcl_monster_eggs:monster_egg_deepslate",
		["shroomlight"] = "mcl_crimson:shroomlight",
		["polished_blackstone"] = "mcl_blackstone:blackstone_polished",
	},
	["unmapped_known_gaps"] = {
		["petrified_oak_slab"] = "Vestigial pre-Beta 1.8 Minecraft block (old oak slab, kept only for old-world compatibility). No Mineclonia equivalent expected to exist; falls back to the oak slab family.",
		["tripwire"] = "No tripwire node registration found anywhere in Mineclonia's source.",
		["tripwire_hook"] = "No tripwire hook node registration found anywhere in Mineclonia's source.",
		["bubble_column"] = "No bubble column node registration found anywhere in Mineclonia's source (only unrelated bubble *particle* effects in brewing/fishing/enchanting).",
	},
	["color_rgb_hex"] = {
		["white"] = "#d0d6d7",
		["light_gray"] = "#818177",
		["gray"] = "#383c40",
		["black"] = "#080a10",
		["purple"] = "#7b2fbe",
		["blue"] = "#3c44aa",
		["light_blue"] = "#3ab3da",
		["cyan"] = "#158991",
		["green"] = "#546d1b",
		["lime"] = "#71b31a",
		["yellow"] = "#f6d51b",
		["brown"] = "#603a1f",
		["orange"] = "#e17a15",
		["red"] = "#a12722",
		["magenta"] = "#c74ebd",
		["pink"] = "#eb9aac",
	},
	["mapart_palette"] = {
		{
			["node"] = "mcl_colorblocks:concrete_white",
			["rgb"] = {
				209,
				214,
				215,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_silver",
			["rgb"] = {
				129,
				129,
				119,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_grey",
			["rgb"] = {
				57,
				60,
				64,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_black",
			["rgb"] = {
				8,
				10,
				16,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_red",
			["rgb"] = {
				147,
				34,
				34,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_orange",
			["rgb"] = {
				226,
				101,
				1,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_yellow",
			["rgb"] = {
				241,
				178,
				22,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_lime",
			["rgb"] = {
				97,
				172,
				25,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_green",
			["rgb"] = {
				75,
				94,
				37,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_cyan",
			["rgb"] = {
				22,
				123,
				140,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_light_blue",
			["rgb"] = {
				37,
				141,
				201,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_blue",
			["rgb"] = {
				46,
				49,
				148,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_purple",
			["rgb"] = {
				103,
				33,
				159,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_magenta",
			["rgb"] = {
				172,
				50,
				162,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_pink",
			["rgb"] = {
				213,
				103,
				145,
			},
		},
		{
			["node"] = "mcl_colorblocks:concrete_brown",
			["rgb"] = {
				99,
				61,
				32,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_white",
			["rgb"] = {
				213,
				197,
				184,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_silver",
			["rgb"] = {
				150,
				129,
				117,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_grey",
			["rgb"] = {
				110,
				92,
				85,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_black",
			["rgb"] = {
				70,
				53,
				46,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_red",
			["rgb"] = {
				160,
				82,
				67,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_orange",
			["rgb"] = {
				157,
				95,
				70,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_yellow",
			["rgb"] = {
				177,
				128,
				52,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_lime",
			["rgb"] = {
				106,
				135,
				74,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_green",
			["rgb"] = {
				75,
				102,
				64,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_cyan",
			["rgb"] = {
				71,
				108,
				124,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_light_blue",
			["rgb"] = {
				91,
				128,
				172,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_blue",
			["rgb"] = {
				69,
				91,
				143,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_purple",
			["rgb"] = {
				82,
				72,
				124,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_magenta",
			["rgb"] = {
				150,
				80,
				86,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_pink",
			["rgb"] = {
				165,
				80,
				77,
			},
		},
		{
			["node"] = "mcl_colorblocks:hardened_clay_brown",
			["rgb"] = {
				96,
				69,
				61,
			},
		},
		{
			["node"] = "mcl_wool:white",
			["rgb"] = {
				213,
				199,
				183,
			},
		},
		{
			["node"] = "mcl_wool:silver",
			["rgb"] = {
				143,
				134,
				135,
			},
		},
		{
			["node"] = "mcl_wool:grey",
			["rgb"] = {
				96,
				87,
				88,
			},
		},
		{
			["node"] = "mcl_wool:black",
			["rgb"] = {
				46,
				42,
				42,
			},
		},
		{
			["node"] = "mcl_wool:red",
			["rgb"] = {
				132,
				42,
				46,
			},
		},
		{
			["node"] = "mcl_wool:orange",
			["rgb"] = {
				189,
				106,
				46,
			},
		},
		{
			["node"] = "mcl_wool:yellow",
			["rgb"] = {
				202,
				163,
				70,
			},
		},
		{
			["node"] = "mcl_wool:lime",
			["rgb"] = {
				108,
				151,
				77,
			},
		},
		{
			["node"] = "mcl_wool:green",
			["rgb"] = {
				53,
				91,
				51,
			},
		},
		{
			["node"] = "mcl_wool:cyan",
			["rgb"] = {
				30,
				94,
				113,
			},
		},
		{
			["node"] = "mcl_wool:light_blue",
			["rgb"] = {
				92,
				131,
				181,
			},
		},
		{
			["node"] = "mcl_wool:blue",
			["rgb"] = {
				43,
				73,
				126,
			},
		},
		{
			["node"] = "mcl_wool:purple",
			["rgb"] = {
				78,
				57,
				102,
			},
		},
		{
			["node"] = "mcl_wool:magenta",
			["rgb"] = {
				141,
				86,
				126,
			},
		},
		{
			["node"] = "mcl_wool:pink",
			["rgb"] = {
				171,
				92,
				108,
			},
		},
		{
			["node"] = "mcl_wool:brown",
			["rgb"] = {
				86,
				57,
				43,
			},
		},
	},
	["literal_nodes"] = {
		"mcl_amethyst:amethyst_block",
		"mcl_amethyst:amethyst_cluster",
		"mcl_amethyst:budding_amethyst_block",
		"mcl_amethyst:calcite",
		"mcl_amethyst:tinted_glass",
		"mcl_anvils:anvil",
		"mcl_anvils:anvil_damage_1",
		"mcl_anvils:anvil_damage_2",
		"mcl_armor_stand:armor_stand",
		"mcl_bamboo:bamboo_big",
		"mcl_bamboo:bamboo_big_leafbig",
		"mcl_bamboo:bamboo_big_leafsmall",
		"mcl_bamboo:bamboo_mosaic",
		"mcl_bamboo:bamboo_shoot",
		"mcl_bamboo:bamboo_small",
		"mcl_bamboo:bamboo_small_leafbig",
		"mcl_bamboo:bamboo_small_leafsmall",
		"mcl_bamboo:scaffolding",
		"mcl_bamboo:scaffolding_horizontal",
		"mcl_banners:hanging_banner",
		"mcl_banners:standing_banner",
		"mcl_barrels:barrel_closed",
		"mcl_barrels:barrel_open",
		"mcl_beacons:beacon",
		"mcl_beacons:beacon_beam",
		"mcl_beds:respawn_anchor",
		"mcl_beds:respawn_anchor_charged_",
		"mcl_beehives:bee_nest",
		"mcl_beehives:bee_nest_5",
		"mcl_beehives:beehive",
		"mcl_beehives:beehive_5",
		"mcl_bells:bell",
		"mcl_bells:bell_ceiling",
		"mcl_bells:bell_wall",
		"mcl_blackstone:basalt",
		"mcl_blackstone:basalt_polished",
		"mcl_blackstone:basalt_smooth",
		"mcl_blackstone:blackstone",
		"mcl_blackstone:blackstone_brick_polished",
		"mcl_blackstone:blackstone_brick_polished_cracked",
		"mcl_blackstone:blackstone_chiseled_polished",
		"mcl_blackstone:blackstone_gilded",
		"mcl_blackstone:blackstone_polished",
		"mcl_blackstone:nether_gold",
		"mcl_blackstone:quartz_brick",
		"mcl_blackstone:soul_fire",
		"mcl_blackstone:soul_soil",
		"mcl_books:bookshelf",
		"mcl_brewing:stand_000",
		"mcl_brewing:stand_001",
		"mcl_brewing:stand_010",
		"mcl_brewing:stand_011",
		"mcl_brewing:stand_100",
		"mcl_brewing:stand_101",
		"mcl_brewing:stand_110",
		"mcl_brewing:stand_111",
		"mcl_cake:cake",
		"mcl_candles:candle_",
		"mcl_candles:candle_cake",
		"mcl_candles:candle_cake_lit",
		"mcl_candles:candle_lit_",
		"mcl_cartography_table:cartography_table",
		"mcl_cauldrons:cauldron",
		"mcl_chests:ender_chest",
		"mcl_chests:ender_chest_small",
		"mcl_cocoas:cocoa_",
		"mcl_colorblocks:concrete_",
		"mcl_colorblocks:concrete_powder_",
		"mcl_colorblocks:glazed_terracotta_",
		"mcl_colorblocks:hardened_clay",
		"mcl_colorblocks:hardened_clay_",
		"mcl_commandblock:commandblock_off",
		"mcl_commandblock:commandblock_on",
		"mcl_compass:lodestone",
		"mcl_composters:composter",
		"mcl_composters:composter_ready",
		"mcl_conduits:conduit",
		"mcl_copper:block",
		"mcl_copper:block_raw",
		"mcl_copper:bulb",
		"mcl_copper:stone_with_copper",
		"mcl_core:andesite",
		"mcl_core:andesite_smooth",
		"mcl_core:barrier",
		"mcl_core:bedrock",
		"mcl_core:bone_block",
		"mcl_core:brick_block",
		"mcl_core:cactus",
		"mcl_core:cactus_flower",
		"mcl_core:clay",
		"mcl_core:coalblock",
		"mcl_core:coarse_dirt",
		"mcl_core:cobble",
		"mcl_core:cobweb",
		"mcl_core:crying_obsidian",
		"mcl_core:deadbush",
		"mcl_core:diamondblock",
		"mcl_core:diorite",
		"mcl_core:diorite_smooth",
		"mcl_core:dirt",
		"mcl_core:dirt_with_grass",
		"mcl_core:emeraldblock",
		"mcl_core:frosted_ice_",
		"mcl_core:glass",
		"mcl_core:glass_",
		"mcl_core:goldblock",
		"mcl_core:granite",
		"mcl_core:granite_smooth",
		"mcl_core:grass_path",
		"mcl_core:gravel",
		"mcl_core:ice",
		"mcl_core:ironblock",
		"mcl_core:ladder",
		"mcl_core:lapisblock",
		"mcl_core:lava_flowing",
		"mcl_core:lava_source",
		"mcl_core:light_",
		"mcl_core:mossycobble",
		"mcl_core:mycelium",
		"mcl_core:obsidian",
		"mcl_core:packed_ice",
		"mcl_core:podzol",
		"mcl_core:realm_barrier",
		"mcl_core:redsand",
		"mcl_core:redsandstone",
		"mcl_core:redsandstonecarved",
		"mcl_core:redsandstonesmooth",
		"mcl_core:redsandstonesmooth2",
		"mcl_core:reeds",
		"mcl_core:sand",
		"mcl_core:sandstone",
		"mcl_core:sandstonecarved",
		"mcl_core:sandstonesmooth",
		"mcl_core:sandstonesmooth2",
		"mcl_core:slimeblock",
		"mcl_core:snowblock",
		"mcl_core:stone",
		"mcl_core:stone_smooth",
		"mcl_core:stone_with_coal",
		"mcl_core:stone_with_diamond",
		"mcl_core:stone_with_emerald",
		"mcl_core:stone_with_gold",
		"mcl_core:stone_with_iron",
		"mcl_core:stone_with_lapis",
		"mcl_core:stone_with_redstone",
		"mcl_core:stone_with_redstone_lit",
		"mcl_core:stonebrick",
		"mcl_core:stonebrickcarved",
		"mcl_core:stonebrickcracked",
		"mcl_core:stonebrickmossy",
		"mcl_core:vine",
		"mcl_core:void",
		"mcl_core:water_flowing",
		"mcl_core:water_source",
		"mcl_crafting_table:crafting_table",
		"mcl_crimson:crimson_fungus",
		"mcl_crimson:crimson_nylium",
		"mcl_crimson:crimson_roots",
		"mcl_crimson:nether_sprouts",
		"mcl_crimson:shroomlight",
		"mcl_crimson:warped_fungus",
		"mcl_crimson:warped_nylium",
		"mcl_crimson:warped_roots",
		"mcl_crimson:warped_wart_block",
		"mcl_daylight_detector:daylight_detector",
		"mcl_daylight_detector:daylight_detector_inverted",
		"mcl_deepslate:deepslate",
		"mcl_deepslate:deepslate_reinforced",
		"mcl_deepslate:tuff_chiseled",
		"mcl_deepslate:tuff_chiseled_bricks",
		"mcl_dispensers:dispenser",
		"mcl_dispensers:dispenser_down",
		"mcl_dispensers:dispenser_up",
		"mcl_dispensers:dropper",
		"mcl_dispensers:dropper_down",
		"mcl_dispensers:dropper_up",
		"mcl_dripstone:dripstone_block",
		"mcl_dripstone:dripstone_bottom_",
		"mcl_dripstone:dripstone_top_",
		"mcl_enchanting:table",
		"mcl_end:chorus_flower",
		"mcl_end:chorus_flower_dead",
		"mcl_end:chorus_plant",
		"mcl_end:dragon_egg",
		"mcl_end:end_bricks",
		"mcl_end:end_rod",
		"mcl_end:end_stone",
		"mcl_end:purpur_block",
		"mcl_end:purpur_pillar",
		"mcl_farming:beetroot",
		"mcl_farming:beetroot_0",
		"mcl_farming:beetroot_1",
		"mcl_farming:beetroot_2",
		"mcl_farming:carrot",
		"mcl_farming:carrot_",
		"mcl_farming:hay_block",
		"mcl_farming:melontige_",
		"mcl_farming:potato",
		"mcl_farming:potato_",
		"mcl_farming:pumpkin_",
		"mcl_farming:pumpkin_face",
		"mcl_farming:pumpkin_face_light",
		"mcl_farming:soil",
		"mcl_farming:soil_wet",
		"mcl_farming:wheat",
		"mcl_farming:wheat_",
		"mcl_fire:eternal_fire",
		"mcl_fire:fire",
		"mcl_fletching_table:fletching_table",
		"mcl_flowerpots:flower_pot",
		"mcl_flowers:bush",
		"mcl_flowers:fern",
		"mcl_flowers:firefly_bush",
		"mcl_flowers:short_dry_grass",
		"mcl_flowers:tall_dry_grass",
		"mcl_flowers:tallgrass",
		"mcl_flowers:waterlily",
		"mcl_grindstone:grindstone",
		"mcl_honey:honey_block",
		"mcl_honey:honeycomb_block",
		"mcl_hoppers:hopper",
		"mcl_hoppers:hopper_disabled",
		"mcl_hoppers:hopper_side",
		"mcl_hoppers:hopper_side_disabled",
		"mcl_jukebox:jukebox",
		"mcl_lectern:lectern",
		"mcl_lectern:lectern_with_book",
		"mcl_lever:lever_off",
		"mcl_lever:lever_on",
		"mcl_lightning_rods:rod",
		"mcl_lightning_rods:rod_exposed",
		"mcl_lightning_rods:rod_exposed_powered",
		"mcl_lightning_rods:rod_oxidized",
		"mcl_lightning_rods:rod_oxidized_powered",
		"mcl_lightning_rods:rod_powered",
		"mcl_lightning_rods:rod_weathered",
		"mcl_lightning_rods:rod_weathered_powered",
		"mcl_loom:loom",
		"mcl_lush_caves:azalea",
		"mcl_lush_caves:azalea_flowering",
		"mcl_lush_caves:cave_vines",
		"mcl_lush_caves:cave_vines_lit",
		"mcl_lush_caves:dripleaf_big",
		"mcl_lush_caves:dripleaf_big_stem",
		"mcl_lush_caves:dripleaf_big_tipped_full",
		"mcl_lush_caves:dripleaf_big_tipped_half",
		"mcl_lush_caves:dripleaf_small",
		"mcl_lush_caves:dripleaf_small_stem",
		"mcl_lush_caves:hanging_roots",
		"mcl_lush_caves:moss",
		"mcl_lush_caves:moss_carpet",
		"mcl_lush_caves:rooted_dirt",
		"mcl_lush_caves:spore_blossom",
		"mcl_mangrove:mangrove_mud_roots",
		"mcl_mangrove:mangrove_roots",
		"mcl_mangrove:propagule",
		"mcl_mangrove:propagule_hanging_",
		"mcl_mangrove:river_water_logged_roots",
		"mcl_mangrove:water_logged_roots",
		"mcl_maps:filled_map_",
		"mcl_maps:filled_map_hand",
		"mcl_meshhand:hand_crea",
		"mcl_meshhand:hand_surv",
		"mcl_mobspawners:spawner",
		"mcl_mud:mud",
		"mcl_mud:mud_bricks",
		"mcl_mud:packed_mud",
		"mcl_mushrooms:mushroom_brown",
		"mcl_mushrooms:mushroom_red",
		"mcl_nether:ancient_debris",
		"mcl_nether:chiseled_nether_brick",
		"mcl_nether:cracked_nether_brick",
		"mcl_nether:glowstone",
		"mcl_nether:magma",
		"mcl_nether:nether_brick",
		"mcl_nether:nether_lava_flowing",
		"mcl_nether:nether_lava_source",
		"mcl_nether:nether_wart",
		"mcl_nether:nether_wart_0",
		"mcl_nether:nether_wart_1",
		"mcl_nether:nether_wart_2",
		"mcl_nether:nether_wart_block",
		"mcl_nether:netheriteblock",
		"mcl_nether:netherrack",
		"mcl_nether:quartz_block",
		"mcl_nether:quartz_chiseled",
		"mcl_nether:quartz_ore",
		"mcl_nether:quartz_pillar",
		"mcl_nether:quartz_smooth",
		"mcl_nether:red_nether_brick",
		"mcl_nether:soul_sand",
		"mcl_noteblock:noteblock",
		"mcl_observers:observer_down_off",
		"mcl_observers:observer_down_on",
		"mcl_observers:observer_off",
		"mcl_observers:observer_on",
		"mcl_observers:observer_up_off",
		"mcl_observers:observer_up_on",
		"mcl_ocean:dead_",
		"mcl_ocean:dried_kelp_block",
		"mcl_ocean:prismarine",
		"mcl_ocean:prismarine_brick",
		"mcl_ocean:prismarine_dark",
		"mcl_ocean:sea_lantern",
		"mcl_ocean:sea_pickle_",
		"mcl_ocean:seagrass_",
		"mcl_pale_oak:block_of_resin",
		"mcl_pale_oak:chiseled_resin_brick",
		"mcl_pale_oak:hanging_moss",
		"mcl_pale_oak:hanging_moss_tip",
		"mcl_pale_oak:pale_moss",
		"mcl_pale_oak:pale_moss_carpet",
		"mcl_pale_oak:resin_brick_block",
		"mcl_pistons:piston_off",
		"mcl_pistons:piston_on",
		"mcl_pistons:piston_pusher",
		"mcl_pistons:piston_pusher_sticky",
		"mcl_pistons:piston_sticky_off",
		"mcl_pistons:piston_sticky_on",
		"mcl_portals:end_portal_frame",
		"mcl_portals:end_portal_frame_eye",
		"mcl_portals:portal",
		"mcl_portals:portal_end",
		"mcl_portals:portal_gateway",
		"mcl_pottery_sherds:pot",
		"mcl_powder_snow:powder_snow",
		"mcl_redstone_lamp:lamp_off",
		"mcl_redstone_lamp:lamp_on",
		"mcl_redstone_torch:redstoneblock",
		"mcl_repeaters:repeater_off_",
		"mcl_repeaters:repeater_off_locked",
		"mcl_repeaters:repeater_on_",
		"mcl_repeaters:repeater_on_locked",
		"mcl_sculk:catalyst",
		"mcl_sculk:sculk",
		"mcl_sculk:sensor",
		"mcl_sculk:shrieker",
		"mcl_sculk:vein",
		"mcl_smithing_table:table",
		"mcl_sponges:sponge",
		"mcl_sponges:sponge_wet",
		"mcl_sponges:sponge_wet_river_water",
		"mcl_stonecutter:stonecutter",
		"mcl_target:target_off",
		"mcl_target:target_on",
		"mcl_tnt:tnt",
		"mcl_tools:heavy_core",
		"mcl_trial_spawners:ominous_trialspawner",
		"mcl_trial_spawners:ominous_trialspawner_on",
		"mcl_trial_spawners:trialspawner",
		"mcl_trial_spawners:trialspawner_on",
		"mcl_villages:building_block",
		"mcl_villages:crop_",
		"mcl_villages:no_paths",
		"mcl_villages:path_endpoint",
		"mcl_villages:village_block",
		"mclx_core:river_water_flowing",
		"mclx_core:river_water_source",
	},
}
