-- Minimal Minecraft Java item id -> Mineclonia item id table.
--
-- data.lua carries the BLOCK palette and is generated by
-- spawnmasons/import_tools/gen_lua_data.py from mc_to_mcl.json. Most items
-- map to the same name as their corresponding block -- e.g.
-- minecraft:diamond -> mcl_core:diamond, minecraft:iron_ingot ->
-- mcl_core:iron_ingot. A handful don't (filled_map, written_book, the
-- banner variants, etc.) and need this file.
--
-- Item NBT the importer cares about:
--   Item.id      - the "minecraft:foo" string; what this table translates
--   Item.Count   - 1-127 stack size (1 byte in modern NBT)
--   Item.tag     - sub-record with damage, enchantments, custom name, etc.
--                  -- only Damage (a.k.a. meta) is currently preserved
--                  -- (which is what most 1.13+ captures actually use,
--                  -- since enchantments moved into separate fields in
--                  -- 1.20.5).
--
-- Items not in this table are dropped with a warning. The audit at
-- /tmp/museum_audit.json is the canonical list of items seen -- if a real
-- item ID is missing from this table, add the mapping.

local M = {}

local function add(vanilla, mcl)
	M[vanilla] = mcl
end

-- Bulk-add: every block in `data.lua` named "mcl_*:foo" exists as an
-- item of the same id when its mod exposes one, which most do. We start
-- the table with the safe defaults; specific overrides below fix the few
-- items whose itemstring differs from the node name.
local item_block_module = {
	-- Note: this is best-effort. Run the audit before adding more entries
	-- blindly -- some block names are also itemstring names (most are),
	-- some aren't (e.g. mcl_signs:sign_oak vs. minecraft:oak_sign).
}

local function default_namespace(v)
	-- Translate a vanilla `minecraft:foo` to its most likely Mineclonia
	-- counterpart for items that have no specific override. This is a
	-- guess; the override table below is authoritative.
	local body = v:match("^minecraft:(.+)$")
	if not body then return nil end

	-- A handful of well-known translations. The rest fall back to
	-- mcl_core:<body>, which is wrong for some items but at least gives
	-- a non-empty itemstring for the importer to attempt to place --
	-- and players see "missing item: mcl_core:foo" rather than a silent
	-- empty slot.
	local overrides = {
		filled_map = "mcl_maps:filled_map",
		book = "mcl_books:book",
		writable_book = "mcl_books:book",
		written_book = "mcl_books:written_book",
		enchanted_book = "mcl_books:enchanted_book",
		knowledge_book = "mcl_books:knowledge_book",
		oak_sign = "mcl_signs:sign_oak",
		spruce_sign = "mcl_signs:sign_spruce",
		birch_sign = "mcl_signs:sign_birch",
		jungle_sign = "mcl_signs:sign_jungle",
		acacia_sign = "mcl_signs:sign_acacia",
		dark_oak_sign = "mcl_signs:sign_dark_oak",
		mangrove_sign = "mcl_signs:sign_mangrove",
		cherry_sign = "mcl_signs:sign_cherry",
		pale_oak_sign = "mcl_signs:sign_pale_oak",
		bamboo_sign = "mcl_signs:sign_bamboo",
		crimson_sign = "mcl_signs:sign_crimson",
		warped_sign = "mcl_signs:sign_warped",
		white_banner = "mcl_banners:banner_white",
		orange_banner = "mcl_banners:banner_orange",
		magenta_banner = "mcl_banners:banner_magenta",
		light_blue_banner = "mcl_banners:banner_light_blue",
		yellow_banner = "mcl_banners:banner_yellow",
		lime_banner = "mcl_banners:banner_lime",
		pink_banner = "mcl_banners:banner_pink",
		gray_banner = "mcl_banners:banner_gray",
		light_gray_banner = "mcl_banners:banner_light_gray",
		cyan_banner = "mcl_banners:banner_cyan",
		purple_banner = "mcl_banners:banner_purple",
		blue_banner = "mcl_banners:banner_blue",
		brown_banner = "mcl_banners:banner_brown",
		green_banner = "mcl_banners:banner_green",
		red_banner = "mcl_banners:banner_red",
		black_banner = "mcl_banners:banner_black",
		shield = "mcl_banners:shield",
		-- Was "mcl_core:totem" (guessed, never registered -- found
		-- 2026-09-19 while unit-testing unrelated merge logic against a
		-- fake ItemStack of that name; real totems live in their own
		-- mod, confirmed via mods/ITEMS/mcl_totems/init.lua).
		totem_of_undying = "mcl_totems:totem",
		clock = "mcl_clock:clock",
		compass = "mcl_compass:compass",
		recovery_compass = "mcl_compass:recovery_compass",
		spyglass = "mcl_spyglass:spyglass",
		carved_pumpkin = "mcl_pumpkin:carved_pumpkin",
		ender_pearl = "mcl_throwing:ender_pearl",
		snowball = "mcl_throwing:snowball",
		flint_and_steel = "mcl_fire:flint_and_steel",
		end_crystal = "mcl_end_crystal:end_crystal",
		music_disc_13 = "mcl_music_discs:disc_13",
		music_disc_cat = "mcl_music_discs:disc_cat",
		music_disc_blocks = "mcl_music_discs:disc_blocks",
		music_disc_chirp = "mcl_music_discs:disc_chirp",
		music_disc_far = "mcl_music_discs:disc_far",
		music_disc_mall = "mcl_music_discs:disc_mall",
		music_disc_mellohi = "mcl_music_discs:disc_mellohi",
		music_disc_stal = "mcl_music_discs:disc_stal",
		music_disc_strad = "mcl_music_discs:disc_strad",
		music_disc_ward = "mcl_music_discs:disc_ward",
		music_disc_11 = "mcl_music_discs:disc_11",
		music_disc_wait = "mcl_music_discs:disc_wait",
		music_disc_otherside = "mcl_music_discs:disc_otherside",
		music_disc_5 = "mcl_music_discs:disc_5",
		music_disc_pigstep = "mcl_music_discs:disc_pigstep",
		music_disc_relic = "mcl_music_discs:disc_relic",
		bamboo_chest_raft = "mcl_boats:chest_raft_bamboo",
		firework_rocket = "mcl_fireworks:rocket",
		leather = "mcl_mobitems:leather",
		bone = "mcl_mobitems:bone",
		feather = "mcl_mobitems:feather",
		egg = "mcl_mobitems:egg",
		ink_sac = "mcl_dye:ink_sac",
		glow_ink_sac = "mcl_dye:glow_ink_sac",
		bow = "mcl_bows:bow",
		crossbow = "mcl_bows:crossbow",
		arrow = "mcl_bows:arrow",
		firework_star = "mcl_fireworks:star",
		potion = "mcl_potions:potion",
		splash_potion = "mcl_potions:splash_potion",
		lingering_potion = "mcl_potions:lingering_potion",
		glass_bottle = "mcl_potions:glass_bottle",
		goat_horn = "mcl_goat_horn:goat_horn",
		nether_star = "mcl_nether:nether_star",
		diamond_horse_armor = "mcl_armor:horse_diamond",
		golden_horse_armor = "mcl_armor:horse_gold",
		iron_horse_armor = "mcl_armor:horse_iron",
		leather_horse_armor = "mcl_armor:horse_leather",
		dried_kelp = "mcl_ocean:dried_kelp",
		glowstone_dust = "mcl_nether:glowstone_dust",
		enchanted_golden_apple = "mcl_core:gold_apple_enchanted",
		golden_apple = "mcl_core:gold_apple",
		sweet_berries = "mcl_berries:sweet_berries",
		glow_berries = "mcl_berries:glow_berries",
		shulker_shell = "mcl_chests:shulker_shell",
		beacon = "mcl_beacons:beacon",
		prismarine_shard = "mcl_ocean:prismarine_shard",
		prismarine_crystals = "mcl_ocean:prismarine_crystals",
		brick = "mcl_core:brick",
		nether_brick = "mcl_nether:nether_brick",
		melon = "mcl_farming:melon",
		paper = "mcl_books:paper",
		name_tag = "mcl_mobitems:name_tag",
		lead = "mcl_mobitems:lead",
		saddle = "mcl_mobitems:saddle",
		bucket = "mcl_buckets:bucket_empty",
		water_bucket = "mcl_buckets:bucket_water",
		lava_bucket = "mcl_buckets:bucket_lava",
		milk_bucket = "mcl_buckets:bucket_milk",
		cod_bucket = "mcl_buckets:bucket_cod",
		salmon_bucket = "mcl_buckets:bucket_salmon",
		tropical_fish_bucket = "mcl_buckets:bucket_tropical_fish",
		pufferfish_bucket = "mcl_buckets:bucket_pufferfish",
		axolotl_bucket = "mcl_buckets:bucket_axolotl",
		tadpole_bucket = "mcl_buckets:bucket_tadpole",
		bookshelf = "mcl_books:bookshelf",
	}
	if overrides[body] then return overrides[body] end
	return "mcl_core:" .. body
end

-- Build the table on first access.
M.resolve = function(vanilla_id)
	if not vanilla_id or type(vanilla_id) ~= "string" then return nil end
	if M[vanilla_id] then return M[vanilla_id] end
	local mcl = default_namespace(vanilla_id)
	M[vanilla_id] = mcl -- cache
	return mcl
end

-- Returns a list of vanilla ids we couldn't translate.
M.unknown_cache = {}
M.unknown = function(vanilla_id)
	return M.unknown_cache[vanilla_id]
end

return M
