-- Biome-matched placement search for museum-import-kit (2026-09-19, owner
-- request): Mineclonia's biome/temperature is a deterministic noise field,
-- global to the world -- queryable at any (x,z) with no chunk generation
-- needed, via mods/MAPGEN/mcl_levelgen's own `level:index_biomes(x,y,z)`
-- (exercised standalone by that mod's own biomedemo.lua -- this script
-- follows the exact same standalone-load pattern). Given each base's real
-- captured biome signature (from tools/source_biomes.lua, generated by
-- import_tools/biome_survey.py from the real source region files), this
-- searches a large candidate area of the DESTINATION Mineclonia world for
-- the best-matching, non-overlapping placement for every base in the list,
-- so (per the owner's own example) a swamp build doesn't end up in an ice
-- biome.
--
-- Run from this directory: luajit find_biome_placement.lua
-- Requires ~/dev/mineclonia/mods/MAPGEN/mcl_levelgen on disk (reads it via
-- a relative dofile chain, same as biomedemo.lua).

local LEVELGEN_DIR = os.getenv("HOME") .. "/dev/mineclonia/mods/MAPGEN/mcl_levelgen"
local SEED_STRING = "16532709774040603227" -- 2026-09-19 round 21
-- correction history: round 16 used 14103668439108119596 (stale HUD
-- value). Round 17 corrected to 15542141214036103012, confirmed live via
-- core.get_mapgen_setting("seed") at the time -- but that was ITSELF
-- wrong, discovered round 21: map_meta.txt's own real persisted
-- top-level `seed =` line (the authoritative value once a map already
-- has generated terrain -- a world.mt `seed=` pin only takes effect for
-- a genuinely fresh/empty map, not retroactively) showed
-- 16532709774040603227 the whole time, predating this session's
-- round-21 work entirely (file mtime from earlier the same day). Round
-- 17's rebuild must have silently reseeded yet again despite the pin.
-- Reconfirmed THIS value live via core.get_mapgen_setting("seed") too,
-- not just the file, before trusting it -- both agree. world.mt now
-- pins this value in both museum-playtest and the deployed copy.

local old_cwd_marker = io.open(LEVELGEN_DIR .. "/init.lua")
if not old_cwd_marker then
	error("can't find mcl_levelgen at " .. LEVELGEN_DIR)
end
old_cwd_marker:close()

-- dofile with relative paths inside mcl_levelgen's own init.lua requires
-- the CWD to actually be that directory (same constraint biomedemo.lua
-- has). Shell out via popen isn't available for chdir in plain Lua, so
-- this script must itself be invoked with that as CWD -- do it here via
-- package-relative dofile instead: load with an absolute prefix override.
package.path = LEVELGEN_DIR .. "/?.lua;" .. package.path

local function dofile_in(dir, name)
	local f = assert(loadfile(dir .. "/" .. name))
	return f()
end

-- mcl_levelgen/init.lua uses `dofile(prefix .. "/x.lua")` with prefix="."
-- relative to CWD. Simplest robust approach: actually chdir there via
-- os.execute is not available either (no os.chdir in stock Lua without
-- posix lib) -- instead just require the caller to `cd` into
-- mcl_levelgen first. Document this clearly rather than fighting it.
assert(io.open("init.lua", "r"),
	"run this script from inside " .. LEVELGEN_DIR .. " (cwd must be that directory -- " ..
	"see this file's own header comment; mcl_levelgen's init.lua dofiles its " ..
	"siblings with a CWD-relative path)")

dofile("init.lua")

local seed = mcl_levelgen.ull(0, 0)
assert(mcl_levelgen.stringtoull(seed, SEED_STRING), "bad seed string")
mcl_levelgen.assign_biome_ids({})
local level = mcl_levelgen.make_overworld_preset(seed)

-- Real per-base biome histograms + footprint sizes, generated by
-- import_tools/biome_survey.py from the actual source region files (see
-- that file's own header for how -- and why -- the numbers are what they
-- are, including the Tactical Nuke surface-material fallback).
local sources = dofile("/Volumes/Dara/dev/museum-import-kit/tools/source_biomes.lua")

-- ---------------------------------------------------------------------
-- Search parameters
-- ---------------------------------------------------------------------
local SEARCH_X_MIN, SEARCH_X_MAX = -3000, 9000
local SEARCH_Z_MIN, SEARCH_Z_MAX = -3000, 9000
local COARSE_STEP = 250      -- candidate anchor grid spacing
local SAMPLE_STEP = 200      -- how densely to sample biomes WITHIN a candidate footprint
local Y_SAMPLE = 64          -- matches biomedemo.lua's own sample height

local function normalize(counts)
	local total = 0
	for _, c in pairs(counts) do total = total + c end
	local frac = {}
	for name, c in pairs(counts) do frac[name] = c / total end
	return frac
end

-- Overlap-coefficient similarity: sum of min(source_frac, dest_frac) per
-- biome name, 0..1, 1 = perfect match. Simple, symmetric-ish, and easy to
-- reason about (unlike e.g. cosine similarity, this directly answers "what
-- fraction of the source's real biome mix is actually represented here").
local function score_histograms(source_frac, dest_counts, dest_total)
	local s = 0
	for name, sfrac in pairs(source_frac) do
		local dcount = dest_counts[name] or 0
		local dfrac = dest_total > 0 and (dcount / dest_total) or 0
		s = s + math.min(sfrac, dfrac)
	end
	return s
end

-- Sample the biome mix a base would actually see if placed with its
-- footprint's (x_min,z_min) corner at `anchor_x,anchor_z`.
local function sample_candidate(anchor_x, anchor_z, width, height)
	local counts = {}
	local total = 0
	for x = anchor_x, anchor_x + width, SAMPLE_STEP do
		for z = anchor_z, anchor_z + height, SAMPLE_STEP do
			local name = level:index_biomes(x, Y_SAMPLE, z)
			counts[name] = (counts[name] or 0) + 1
			total = total + 1
		end
	end
	return counts, total
end

local function boxes_overlap(a, b)
	return a.x_min < b.x_max and a.x_max > b.x_min
		and a.z_min < b.z_max and a.z_max > b.z_min
end

-- ---------------------------------------------------------------------
-- Build the candidate list, process bases LARGEST FOOTPRINT FIRST (more
-- constrained -- fewer places a big base can go -- so it gets first pick;
-- smaller bases have an easier time finding a non-overlapping spot after).
-- ---------------------------------------------------------------------
local base_names = {}
for name in pairs(sources) do base_names[#base_names + 1] = name end
table.sort(base_names, function(a, b)
	local aa = sources[a].width * sources[a].height
	local bb = sources[b].width * sources[b].height
	return aa > bb
end)

local claimed = {}
local results = {}

for _, name in ipairs(base_names) do
	local src = sources[name]
	local source_frac = normalize(src.counts)
	local width, height = src.width, src.height

	local best_score, best_x, best_z = -1, nil, nil
	for ax = SEARCH_X_MIN, SEARCH_X_MAX - width, COARSE_STEP do
		for az = SEARCH_Z_MIN, SEARCH_Z_MAX - height, COARSE_STEP do
			local candidate_box = { x_min = ax, x_max = ax + width, z_min = az, z_max = az + height }
			local overlaps = false
			for _, box in ipairs(claimed) do
				if boxes_overlap(candidate_box, box) then overlaps = true; break end
			end
			if not overlaps then
				local dest_counts, dest_total = sample_candidate(ax, az, width, height)
				local sc = score_histograms(source_frac, dest_counts, dest_total)
				if sc > best_score then
					best_score, best_x, best_z = sc, ax, az
				end
			end
		end
	end

	assert(best_x, "no non-overlapping placement found for " .. name .. " -- widen SEARCH_* bounds")
	local box = { x_min = best_x, x_max = best_x + width, z_min = best_z, z_max = best_z + height }
	claimed[#claimed + 1] = box
	results[name] = { anchor_x = best_x, anchor_z = best_z, score = best_score, width = width, height = height }
	io.stderr:write(string.format("%s -> anchor (%d, %d), score %.3f\n", name, best_x, best_z, best_score))
end

-- ---------------------------------------------------------------------
-- Write results for the Python manifest-updater to read.
-- ---------------------------------------------------------------------
local out = io.open("/tmp/biome_placement_results.lua", "w")
out:write("return {\n")
for name, r in pairs(results) do
	out:write(string.format("  [%q] = { anchor_x = %d, anchor_z = %d, score = %.4f },\n",
		name, r.anchor_x, r.anchor_z, r.score))
end
out:write("}\n")
out:close()
print("wrote /tmp/biome_placement_results.lua")
